CC       = go build
BUILDDIR = ./bin
PRGS     = server client #test

LINES = $(shell wc -l < taps/taps_global.go)

all: $(PRGS)

.PHONY: server
server: glob
	$(CC) -o $(BUILDDIR)/$@ cmd/server/*.go
	cp -f $(BUILDDIR)/$@ /home/ubuntu/Documents/TAPS-API/server

.PHONY: client
client: glob
	$(CC) -o $(BUILDDIR)/$@ cmd/client/*.go
	cp -f $(BUILDDIR)/$@ /home/ubuntu/Documents/TAPS-API/client
	
.PHONY: test
test:
	$(CC) -o $(BUILDDIR)/$@ cmd/test/*.go

.PHONY: glob
glob:
	echo "// Autogenerated! Do not modify.\npackage glob" > glob/taps_global.go
	sed -n '2,$$p;$(LINES)q' taps/taps_global.go >> glob/taps_global.go

clean:
	rm -f $(BUILDDIR)/*
