CC       = go build
BUILDDIR = ./bin
PRGS     = server client

LINES = $(shell wc -l < taps/global.go)

all: $(PRGS)

.PHONY: server
server: glob
	$(CC) -o $(BUILDDIR)/$@ cmd/server/*.go
	cp -f $(BUILDDIR)/$@ /home/ubuntu/Documents/TAPS-API/server

.PHONY: client
client: glob
	$(CC) -o $(BUILDDIR)/$@ cmd/client/*.go
	cp -f $(BUILDDIR)/$@ /home/ubuntu/Documents/TAPS-API/client

.PHONY: glob
glob:
	echo "// Autogenerated! Do not modify.\npackage glob" > glob/global.go
	sed -n '2,$$p;$(LINES)q' taps/global.go >> glob/global.go

clean:
	rm -f $(BUILDDIR)/*
